const toggle=document.querySelector('.menu-toggle');
const mobileNav=document.getElementById('mobile-nav');
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));toggle.setAttribute('aria-label',open?'Open menu':'Close menu');mobileNav.hidden=open;});
mobileNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileNav.hidden=true;toggle.setAttribute('aria-expanded','false');}));
document.getElementById('year').textContent=new Date().getFullYear();
const inventory={henley:{name:'Burgundy henley top',price:22,image:'assets/henley.webp',description:'Ribbed burgundy henley-style top with lace-trim detailing.'},jeans:{name:'Relaxed fit jeans',price:25,image:'assets/jeans.webp',description:'Easy everyday jeans in a light-blue wash.'},cardigan:{name:'Comfy cardi',price:27,image:'assets/cardigan.webp',description:'Soft-looking blue cable-knit cardigan.'}};
const read=(key,otherwise)=>{try{const val=JSON.parse(localStorage.getItem(key));return val&&typeof val==='object'?val:otherwise}catch{return otherwise}};
let favourites=read('maelinne-favourites',[]);if(!Array.isArray(favourites))favourites=[];
let bag=read('maelinne-bag',{});if(Array.isArray(bag))bag={};
const persist=()=>{try{localStorage.setItem('maelinne-favourites',JSON.stringify(favourites));localStorage.setItem('maelinne-bag',JSON.stringify(bag));}catch{}};
const euros=x=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(x);
const productDialog=document.getElementById('product-dialog'),bagDialog=document.getElementById('cart-dialog');
function render(){document.querySelectorAll('[data-fave]').forEach(b=>{const on=favourites.includes(b.dataset.fave);b.setAttribute('aria-pressed',String(on));b.textContent=on?'♥':'♡';});const fc=document.getElementById('fave-count');fc.textContent=favourites.length;fc.hidden=!favourites.length;const list=document.getElementById('fave-list');list.replaceChildren();if(!favourites.length)list.textContent='Tap a heart above to save a favourite.';for(const id of favourites.filter(x=>inventory[x])){const a=document.createElement('a');a.href='#shop';a.textContent=inventory[id].name;list.append(a);}const count=Object.entries(bag).reduce((s,[id,n])=>s+(inventory[id]?Math.max(0,Number(n)||0):0),0);const el=document.getElementById('cart-count');el.textContent=count;el.hidden=!count;}
function add(id){if(!inventory[id])return;bag[id]=(Number(bag[id])||0)+1;persist();render();renderCart();bagDialog.showModal();}
function renderCart(){const list=document.getElementById('cart-items');list.replaceChildren();let sum=0;for(const [id,qty] of Object.entries(bag)){if(!inventory[id]||qty<=0)continue;const p=inventory[id],row=document.createElement('div');row.className='cart-row';const name=document.createElement('span');name.textContent=p.name+' × '+qty;const price=document.createElement('span');price.textContent=euros(p.price*qty);sum+=p.price*qty;const remove=document.createElement('button');remove.textContent='Remove';remove.setAttribute('aria-label','Remove one '+p.name);remove.addEventListener('click',()=>{bag[id]--;if(bag[id]<=0)delete bag[id];persist();render();renderCart();});row.append(name,price,remove);list.append(row);}if(!list.childElementCount)list.textContent='Your bag is empty.';const total=document.getElementById('cart-total');total.className='cart-total';total.textContent='Example subtotal: '+euros(sum);}
function details(id){const p=inventory[id];if(!p)return;const div=document.getElementById('product-dialog-body');div.replaceChildren();const h=document.createElement('h2');h.id='product-dialog-title';h.textContent=p.name;const content=document.createElement('div');content.className='detail-layout';const image=document.createElement('img');image.src=p.image;image.alt=p.name+' (illustrative)';const info=document.createElement('div');const price=document.createElement('strong');price.textContent=euros(p.price);const desc=document.createElement('p');desc.textContent=p.description;const note=document.createElement('p');note.className='demo-notice';note.textContent='Illustrative product and example price. Sizes, specifications and availability are not confirmed.';const btn=document.createElement('button');btn.className='button button-dark';btn.textContent='Add to demo bag +';btn.addEventListener('click',()=>{productDialog.close();add(id);});info.append(price,desc,note,btn);content.append(image,info);div.append(h,content);productDialog.showModal();}
document.addEventListener('click',e=>{const f=e.target.closest('[data-fave]');if(f){const id=f.dataset.fave;if(favourites.includes(id))favourites=favourites.filter(x=>x!==id);else favourites.push(id);persist();render();return;}const v=e.target.closest('[data-view]');if(v)return details(v.dataset.view);const a=e.target.closest('[data-add]');if(a)return add(a.dataset.add);if(e.target.closest('#cart-open')){renderCart();bagDialog.showModal();return;}if(e.target.closest('[data-close]'))e.target.closest('dialog').close();});
for(const dlg of [productDialog,bagDialog])dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close();});
render();
